#!/usr/bin/env bash
# Display time in minutes from hours 0 to 12
COUNTER=1
HOUR=0
while [ $HOUR -lt 14 ];do
	echo "$COUNTER"
	let COUNTER=COUNTER+1
	if [ $COUNTER -eq 60 ]
	then
		if [ $HOUR -ne 13 ]
		then
			echo "Hour: $HOUR"
		fi
		let COUNTER=1
		let HOUR=HOUR+1
	fi
done
