#!/usr/bin/env bash
# install nginx, redirects
sudo apt-get -y update
sudo apt-get -y install nginx
text="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "/^}/ i $text" /etc/nginx/sites-enabled/default
sudo service nginx restart
