#!/usr/bin/env bash
# install nginx, redirects
apt-get -y update
apt-get -y install nginx
rm /usr/share/nginx/html/index.html
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
replace="server_name localhost;\n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sed -i "s|server_name localhost;|$replace|" /etc/nginx/sites-available/default
service nginx restart
