#!/usr/bin/env bash
# install nginx, redirects
apt-get -y update
apt-get -y install nginx
rm /usr/share/nginx/html/index.html
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
replace="location ~ ^/rewrite_me$ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\tlocation / {"
sed -i "/^}/i $replace/" /etc/nginx/sites-enabled/default
service nginx restart
