#!/usr/bin/env bash
# runs nginx as nginx
sed -i '1 i\user nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill -f apache2
chown nginx: /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sudo -u nginx nginx -c /etc/nginx/nginx.conf
sudo nginx reload
